openapi: 3.0.0
info:
  title: Room API
  description: API para gerenciar salas de reunião
  version: 1.0.0
servers:
  - url: http://localhost:5000/api

paths:
  /rooms:
    post:
      summary: Criar uma nova sala de reunião
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Sala 1"
                  description: O nome da sala
                description:
                  type: string
                  example: "Reunião"
                  description: A descrição da sala
                capacity:
                  type: number
                  example: 10
                  description: A capacidade da sala
      responses:
        '201':
          description: Sala criada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: "60d21b4667d0d8992e610c85"
                  name:
                    type: string
                    example: "Sala 1"
                  description:
                    type: string
                    example: "Reunião"
                  capacity:
                    type: number
                    example: 10
                  isActive:
                    type: boolean
                    example: true
                  createdAt:
                    type: string
                    format: date-time
                    example: "2023-10-01T14:48:00.000Z"
        '400':
          description: Erro nos dados enviados
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        msg:
                          type: string
                          example: "Room name is required"
        '401':
          description: Não autorizado
        '500':
          description: Erro no servidor

    get:
      summary: Listar todas as salas de reunião
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de salas retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: "60d21b4667d0d8992e610c85"
                    name:
                      type: string
                      example: "Sala 1"
                    description:
                      type: string
                      example: "Reunião"
                    capacity:
                      type: number
                      example: 10
                    isActive:
                      type: boolean
                      example: true
                    createdAt:
                      type: string
                      format: date-time
                      example: "2023-10-01T14:48:00.000Z"
        '401':
          description: Não autorizado
        '500':
          description: Erro no servidor

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT